config/routes.rb
Rails.application.routes.draw do
	get 'password_resets/new'

	get 'password_resets/edit'

	get 'sessions/new'

	get 'users/new'

	root 'static_pages#home'
	
	get  '/help', to: 'static_pages#help'

	get  '/about', to: 'static_pages#about'

	get  '/contact', to: 'static_pages#contact'

	get '/signup', to: 'users#new'

	get '/login', to: 'sessions#new'

	post '/login', to: 'sessions#create'

	delete '/logout', to: 'sessions#destroy'

	get '/auth/:provider/callback', to: 'sessions#create'

	resources :users do
		member do
			get :following, :followers
		end
	end

	resources :users

  	resources :account_activations, only: [:edit]

  	resources :password_resets, only: [:new, :create, :edit, :update]

  	resources :microposts, only: [:create, :destroy]

  	resources :relationships, only: [:create, :destroy]

  	resources :sessions, only: [:create, :destroy]
end

app/views/layouts/header/_header.html.erb
                <header>
                    <div class="nav-container">
                        <div class="nav-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navigation" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            </button>                        
                            <%= link_to "sample-app", root_path, id: "logo" %>
                        </div>
                        <nav>
                            <div class="nav-content" id="top-navigation">
                                <ul class="nav-links">
                                    <li><%= link_to "Home", root_path %></li>
                                    <li><%= link_to "Help", help_path %></li>
                                    <% if logged_in? %>
                                        <li><%= link_to "Users", users_path %></li>
                                        <li class="nav-main-dropdown">
                                            <a id="account-dropdown-menu" href="<%= request.original_url %>" data-target="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
                                            <ul class="dropdown-menu" aria-labelledby="accont-dropdown-menu">
                                                <li><%= link_to "Profile", current_user %></li>
                                                <li><%= link_to "Settings", edit_user_path(current_user)  %></li>
                                                <li class="divider"></li>
                                                <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
                                            </ul>
                                        </li>
                                        <% else %>
                                            <li><%= link_to "Log in", login_path %></li>
                                        <% end %>
                                </ul>                                
                            </div>
                        </nav>
                    </div>
                </header>   